---
driver:
  name: vagrant
  vm_hostname: '-vagrant'

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5

suites:
  - name: default
    data_bags_path: 'test/integration/data_bags'
    run_list:
      - recipe[ohai-plugin::default]
    attributes:
